<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Resources\klikety.ico</ApplicationIcon>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Klikety.Tests" />
    <InternalsVisibleTo Include="Klikety.SmokeTests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\config.schema.json" />
    <EmbeddedResource Include="Resources\config.json" />
    <EmbeddedResource Include="Resources\macros.schema.json" />
    <EmbeddedResource Include="Resources\macros.json" />
    <EmbeddedResource Include="Resources\theme.schema.json" />
    <EmbeddedResource Include="Resources\dark.theme.json" />
    <EmbeddedResource Include="Resources\light.theme.json" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\klikety.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.*" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.*" />
  </ItemGroup>

</Project>
